import os
Import ('CEnv')

resources = Split ("""
	clamp-properties-dialog.glade2
	log-window.glade2
	part-browser.glade2
	part-properties-dialog.glade2
	plot-add-function.glade2
	export.glade2
	plot-window.glade2
	properties.glade2
	settings.glade2
	sim-settings.glade2
	simulation.glade2
	splash.glade2
	textbox-properties-dialog.glade2
	print-options.glade2
	view-netlist.glade2
	splash.xpm""")

CEnv.Alias('install', CEnv.Install (os.path.join (CEnv['INSTALL_DIR'], 'share/oregano/dialogs'), resources))

