import os
Import ('CEnv')

resources = Split ("""
	12AX7A.model
	1N4148.model
	1N750.model
	DiodeBridge.model
	NPN.model
	PNP.model
	TLC555.model
	UA741.model
	""")

CEnv.Alias('install', CEnv.Install (os.path.join (CEnv['INSTALL_DIR'], 'share/oregano/models'), resources))
