resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: docker.io/teliaoss/github-pr-resource

- name: copr
  type: registry-image
  source:
    repository: quay.io/ahoi/concourse-copr-resource

resources:
- name: git-clone-resource
  type: git
  icon: git
  source:
    branch: master
    uri: https://github.com/drahnr/oregano.git

- name: git-ci
  type: git
  icon: git
  source:
    branch: master
    uri: https://github.com/drahnr/oregano.git
    paths:
    - .concourse/*
    - .concourse/fedora/*
    - .concourse/ubuntu/*

- name: git-ci-oci-fedora
  type: git
  icon: git
  source:
    branch: master
    uri: https://github.com/drahnr/oregano.git
    paths:
    - .concourse/fedora/*

- name: git-ci-oci-ubuntu
  type: git
  icon: git
  source:
    branch: master
    uri: https://github.com/drahnr/oregano.git
    paths:
    - .concourse/ubuntu/*

- name: git-tag-resource
  type: git
  icon: git
  source:
    tag_filter: "v[0-9]*"
    branch: master
    uri: https://github.com/drahnr/oregano.git

- name: git-pull-request-resource
  type: pull-request
  icon: github
  source:
    repository: drahnr/oregano
    access_token: ((sirmergealot-github-token))


- name: copr-resource
  type: copr
  icon: fedora
  source:
    login: ((copr-login))
    token: ((copr-token))
    url: ((copr-url))

- name: oregano-test-fedora
  type: registry-image
  icon: oci
  source:
    tag: latest
    repository: quay.io/ratpoison/oregano-test-fedora
    username: ((quay-ratpoison-username))
    password: ((quay-ratpoison-password))

- name: oregano-test-ubuntu
  type: registry-image
  icon: oci
  source:
    tag: latest
    repository: quay.io/ratpoison/oregano-test-ubuntu
    username: ((quay-ratpoison-username))
    password: ((quay-ratpoison-password))

- name: deb-release
  type: s3
  icon: debian
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-rc
    regexp: "^(.*).deb$"
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: rpm-release
  type: s3
  icon: fedora
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-rc
    regexp: "^(.*).rpm$"
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: flatpak-release
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-rc
    regexp: "^(.*).flatpak$"
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: source-release
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-rc
    regexp: (.*).tar.xz
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: deb-drop
  type: s3
  icon: debian
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-drop
    regexp: (.*).deb
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: flatpak-drop
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-drop
    regexp: (.*).flatpak
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: rpm-drop
  type: s3
  icon: fedora
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-drop
    regexp: (.*).rpm
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: source-drop
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: oregano-drop
    regexp: (.*).tar.xz
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: gh-release
  type: github-release
  icon: github
  source:
    owner: drahnr
    repository: oregano
    access_token: ((drahnr-github-token))

groups:
- name: release
  jobs:
  - source-release
  - build-pkg-*-release
  - make-release
- name: master
  jobs:
  - build-pkg-deb
  - build-pkg-rpm
  - build-pkg-flatpak
  - compile
- name: pr
  jobs:
  - pr-validate
- name: env
  jobs:
  - oci-fedora
  - oci-ubuntu

jobs:
  - name: oci-fedora
    build_logs_to_retain: 2
    plan:

    - get: git-ci-oci-fedora
      trigger: true
    - get: git-ci

    - task: gen-container
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          CONTEXT: git-ci/.concourse/fedora
        inputs:
        - name: git-ci
        outputs:
        - name: image
        caches:
        - path: cache
        run:
          path: build

    - put: oregano-test-fedora
      params:
        image: image/image.tar

  - name: oci-ubuntu
    build_logs_to_retain: 2
    plan:
    - get: git-ci-oci-ubuntu
      trigger: true
    - get: git-ci

    - task: gen-container
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          CONTEXT: git-ci/.concourse/ubuntu
        inputs:
        - name: git-ci
        outputs:
        - name: image
        caches:
        - path: cache
        run:
          path: build

    - put: oregano-test-ubuntu
      params:
        image: image/image.tar

  - name: pr-validate
    build_logs_to_retain: 20
    public: true
    plan:
    - get: tree
      resource: git-pull-request-resource
      trigger: true

    - put: git-pull-request-resource
      params:
        path: tree
        context: compile
        status: pending

    - in_parallel:
      - get: oregano-test-ubuntu
        trigger: true
      - get: oregano-test-fedora
        trigger: true

    - task: compile
      timeout: 5m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: tree
        run:
          path: sh
          args:
          - -exc
          - |
            ./waf configure build --debug --prefix=/tmp install
            ./build/test/microtests
          dir: tree

      on_success:
        put: git-pull-request-resource
        params:
          path: tree
          context: compile
          status: success

      on_failure:
        put: git-pull-request-resource
        params:
          path: tree
          context: compile
          status: failure

    - in_parallel:
      - put: git-pull-request-resource
        params:
          path: tree
          context: pkg-rpm
          status: pending

      - put: git-pull-request-resource
        params:
          path: tree
          context: pkg-deb
          status: pending

      - put: git-pull-request-resource
        params:
          path: tree
          context: pkg-flatpak
          status: pending

    - in_parallel:
      - task: create-rpm
        timeout: 15m
        image: oregano-test-fedora
        file: tree/.concourse/tasks/pkg-rpm.yml

        on_success:
          put: git-pull-request-resource
          params:
            path: tree
            context: pkg-rpm
            status: success

        on_failure:
          put: git-pull-request-resource
          params:
            path: tree
            context: pkg-rpm
            status: failure

      - task: create-deb
        timeout: 15m
        image: oregano-test-ubuntu
        file: tree/.concourse/tasks/pkg-deb.yml

        on_success:
          put: git-pull-request-resource
          params:
            path: tree
            context: pkg-deb
            status: success

        on_failure:
          put: git-pull-request-resource
          params:
            path: tree
            context: pkg-deb
            status: failure

      - task: create-flatpak
        timeout: 35m
        image: oregano-test-fedora
        file: tree/.concourse/tasks/flatpak.yml

        on_success:
          put: git-pull-request-resource
          params:
            path: tree
            context: pkg-flatpak
            status: success

        on_failure:
          put: git-pull-request-resource
          params:
            path: tree
            context: pkg-flatpak
            status: failure




############### master
  - name: compile
    build_logs_to_retain: 10
    public: true
    plan:
    - in_parallel:
      - get: oregano-test-fedora
        trigger: true
      - get: tree
        resource: git-clone-resource
        trigger: true

    - task: compile
      timeout: 15m
      image: oregano-test-fedora
      file: tree/.concourse/tasks/dist.yml

    - put: source-drop
      params:
        file: dist/oregano-*.tar.xz
        acl: public-read

  - name: build-pkg-rpm
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: oregano-test-fedora
        trigger: true
      - get: tree
        resource: git-clone-resource
        trigger: true
        passed: [compile]

    - task: create-rpm
      timeout: 15m
      image: oregano-test-fedora
      file: tree/.concourse/tasks/pkg-rpm.yml

    - put: rpm-drop
      params:
        file: rpm/oregano*.rpm
        acl: public-read

  - name: build-pkg-deb
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: oregano-test-ubuntu
        trigger: true
      - get: tree
        resource: git-clone-resource
        trigger: true
        passed: [compile]

    - task: create-deb
      timeout: 20m
      image: oregano-test-ubuntu
      file: tree/.concourse/tasks/pkg-deb.yml

    - put: deb-drop
      params:
        file: deb/oregano*.deb
        acl: public-read

  - name: build-pkg-flatpak
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: oregano-test-fedora
        trigger: true
      - get: tree
        resource: git-clone-resource
        trigger: true
        passed: [compile]

    - task: create-flatpak
      timeout: 15m
      image: oregano-test-fedora
      file: tree/.concourse/tasks/flatpak.yml

    - put: flatpak-drop
      params:
        file: flatpak/oregano*.flatpak
        acl: public-read

###############################################################################



  - name: source-release
    build_logs_to_retain: 10
    public: true
    plan:
    - in_parallel:
      - get: oregano-test-fedora
        trigger: true
      - get: tree
        resource: git-tag-resource
        trigger: true

    - task: source
      timeout: 15m
      image: oregano-test-fedora
      file: tree/.concourse/tasks/dist.yml

    - put: source-release
      params:
        file: dist/oregano-*.tar.xz
        acl: public-read

  - name: build-pkg-rpm-release
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: oregano-test-fedora
        trigger: true
      - get: tree
        resource: git-tag-resource
        trigger: true

    - task: create-rpm
      timeout: 15m
      image: oregano-test-fedora
      file: tree/.concourse/tasks/pkg-rpm.yml

    - put: rpm-release
      params:
        file: rpm/oregano*.rpm
        acl: public-read

    - put: copr
      resource: copr-resource
      params:
        rpmbuild_dir: "srpm"
        chroots: ["fedora-rawhide-x86_64", "fedora-34-x86_64", "fedora-33-x86_64"]
        enable_net: false
        max_n_bytes: 250000000
        project_id: 825
        regex: ".*oregano-.*\\.src\\.rpm$"

  - name: build-pkg-deb-release
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: oregano-test-ubuntu
        trigger: true
      - get: tree
        resource: git-tag-resource
        trigger: true

    - task: create-deb
      timeout: 15m
      image: oregano-test-ubuntu
      file: tree/.concourse/tasks/pkg-deb.yml

    - put: deb-release
      params:
        file: deb/oregano*.deb
        acl: public-read

  - name: build-pkg-flatpak-release
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: oregano-test-fedora
        trigger: true
      - get: tree
        resource: git-tag-resource
        trigger: true

    - task: create-flatpak
      timeout: 30m
      image: oregano-test-fedora
      file: tree/.concourse/tasks/flatpak.yml

    - put: flatpak-release
      params:
        file: flatpak/oregano*.flatpak
        acl: public-read

  - name: make-release
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: git-tag-resource
        passed: [source-release,build-pkg-rpm-release, build-pkg-deb-release]
        trigger: true
      - get: oregano-test-fedora
      - get: source-release
        passed: [source-release]
      - get: rpm-release
        passed: [build-pkg-rpm-release]
      - get: deb-release
        passed: [build-pkg-deb-release]
      - get: flatpak-release
        passed: [build-pkg-flatpak-release]

    - task: tag2file
      timeout: 5m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-tag-resource
        - name: source-release
        - name: deb-release
        - name: rpm-release
        - name: flatpak-release
        outputs:
        - name: release-info
        run:
          path: sh
          args:
          - -exc
          - |
            git rev-parse HEAD > ../release-info/COMMITISH
            ./waf --version
            ./waf version
            cat VERSION > ../release-info/TAG
            echo "oregano" > ../release-info/NAME
            echo "Yet another release" > ../release-info/BODY
          dir: git-tag-resource

    - put: gh-release
      params:
        tag_prefix: v
        name: release-info/NAME
        tag: release-info/TAG
        body: release-info/BODY
        commitish: release-info/COMMITISH
        globs:
        - source-release/oregano-*.tar.xz
        - rpm-release/oregano-*.rpm
        - deb-release/oregano_*.deb
        - flatpak-release/oregano*.flatpak
