import os
Import ('CEnv')

resources = Split ("""
	cmos.oreglib
	cpu.oreglib
	default.oreglib
	interface.oreglib
	linear.oreglib
	memory.oreglib
	miscellaneous.oreglib
	opamplib.oreglib
	peripheral.oreglib
	power.oreglib
	ttl.oreglib
	""")

CEnv.Alias('install', CEnv.Install (os.path.join (CEnv['INSTALL_DIR'], 'share/oregano/libraries'), resources))

