.\" Copyrights 2000 by Hugo van der Merwe <hvdm@debian.org>
.\" This is free documentation, see the latest version of the GNU Free
.\" Documentation License for copying conditions. There is NO warranty.
.TH OREGANO 1 "September 12, 2004" "oregano"

.SH NAME
oregano \- GNOME application for schematic capture of electrical circuits

.SH SYNOPSIS
.B oregano

.SH DESCRIPTION
This manual page briefly documents
.B oregano.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B oregano
is an application for schematic capture and printing of electrical circuits.
It can also be used for simulation if you have NG-Spice or Gnucap.

.SH BUGS
This is under active development and things might not work as expected.
Regarding backwards compatibility, when opening oregano 0.23 files some wires
might be out of place, and the probes will not be present.
.PP
Undo, redo has not yet been implemented.

.SH SEE ALSO
.B oregano
includes online help, found in the Help menu of the program.
Relevant documentation included with the source can also be found
in /usr/share/doc/oregano/

.SH AUTHOR

.B oregano
was written by Richard Hult <rhult@codefactory.se>. And retaken by Ricardo
Markiewicz <rmarkie@fi.uba.ar> and Andres de Barbara <adebarbara@fi.uba.ar>.
.PP
This manual page was originally written by Hugo van der Merwe 
<hvdm@debian.org> for the Debian GNU/Linux system. Later modified by
Maximiliano Curia <maxy@gnuservers.com.ar>.
