#! /usr/bin/env python
# encoding: utf-8

import os
from waflib import Logs as logs

def makepot(ctx):
	os.system ('cd po && intltool-update --headers --verbose')

def build(bld):
	bld(
		features='intltool_po',
		appname=bld.env.appname,
		podir='.',
		install_path="${LOCALEDIR}")

