#! /usr/bin/env python
# encoding: utf-8

top = '..'
out = '../build'

from waflib import Logs as logs
from waflib import Utils as utils

def options(opts):
    pass

def configure(conf):
    pass

def build(bld):
	bld.load('gtkbuilder', tooldir='waftools')

	if bld.cmd == 'install':
		if not bld.env.no_update_desktop_database:
			try:
				bld.exec_command(['update-desktop-database', utils.subst_vars('${DATADIR}/applications', bld.env)])
			except:
				logs.warn('Failed to execute xdg desktop database update.')

		if not bld.env.no_update_mime_database:
			try:
				bld.exec_command(['update-mime-database', utils.subst_vars('${DATADIR}/mime', bld.env)])
			except:
				logs.warn('Failed to execute xdg mime database update.')


	bld.install_as ('${DATADIR}/mime-info/oregano.keys', 'mime/oregano.keys.in')
	bld.install_files ('${DATADIR}/icons/hicolor/48x48/apps/', 'mime/oregano.png')
	bld.install_files ('${DATADIR}/icons/hicolor/scalable/apps/', 'mime/oregano.svg')
	if bld.cmd == 'install':
		if not bld.env.no_update_icon_cache:
			try:
				bld.exec_command(['gtk-update-icon-cache', utils.subst_vars('${DATADIR}/icons/hicolor', bld.env)])
			except:
				logs.warn('Failed to execute xdg mime database update.')

	bld(source=bld.path.ant_glob('xml/*.ui'), install_path = bld.env.path_ui)

	bld(
		features  = 'subst',
		source    = 'oregano.desktop.in',
		target    = 'oregano.desktop',
		install_path = '${DATADIR}/applications',
	)

	bld(
		features  = 'subst',
		source    = 'mime/oregano-mimetypes.xml.in',
		target    = 'mime/oregano.xml',
		install_path = '${DATADIR}/mime/packages/',
	)

	bld(rule = "groff ${SRC} > ${TGT}", source="oregano.MAN.in", target="oregano.5")
	bld.install_files ('${MANDIR}/man5', 'oregano.5')
