#! /usr/bin/env python
# encoding: utf-8

from waflib import Logs as logs

def build(bld):
	if bld.cmd == 'install':
		bld.install_files ('${DATADIR}/mime-info/', locate('(\./)?mime/.+\.keys'))
		bld.install_files ('${DATADIR}/icons/hicolor/48x48/apps/', locate('(\./)?mime/.+\.(png|svg)'))
		bld.install_files ('${DATADIR}', locate('(\./)?.*\.lang'))

		bld.install_files (bld.env.path_model, locate('(\./)?/models/.+\.model'))
		bld.install_files (bld.env.path_examples, locate('(\./)?examples/.+'))
		bld.install_files (bld.env.path_partslib, locate('(\./)?libraries/.+\.oreglib'))
		bld.install_files (bld.env.path_ui, locate('(\./)?xml/.+\.ui'))

		try:
			bld.exec_command(["update-mime-database", Utils.subst_vars("${DATADIR}/mime", bld.env)])
			bld.exec_command(["update-desktop-database", Utils.subst_vars("${DATADIR}/applications", bld.env)])
		except:
			logs.warn("Failed to execute mime or desktop database update")

	bld(
		features  = "intltool_in",
		podir     = "../po",
		flags     = ["-d", "-q", "-u", "-c"],
		source    = 'oregano.desktop.in',
		target    = 'oregano.desktop',
		install_path = "${DATADIR}/applications",
	)

	bld(
		features  = "intltool_in",
		podir     = "../po",
		flags     = ["-x", "-q", "-u", "-c"],
		source    = 'mime/oregano-mimetypes.xml.in',
		target    = 'mime/oregano.xml',
		install_path = "${DATADIR}/mime/packages/",
	)
