FROM ubuntu:latest
ENV DRONE_SERVER_PORT :80

RUN apt-get update -y
RUN apt-get install -y libglib2.0-dev intltool libgtk-3-dev libxml2-dev libgoocanvas-2.0-dev libgtksourceview-3.0-dev gnucap ngspice

COPY id_rsa ~/.ssh/
COPY id_rsa.pub ~/.ssh/
