import os
Import ('CEnv')

SrcEnv = CEnv.Copy ()

LocaleDir         = '-DGNOMELOCALEDIR=\\""'+SrcEnv['DATADIR']+'/locale"\\"'
OreganoGladeDir   = '-DOREGANO_GLADEDIR=\\""'+SrcEnv['OREGANODIR']+'/dialogs"\\"'
OreganoLibraryDir = '-DOREGANO_LIBRARYDIR=\\""'+SrcEnv['OREGANODIR']+'/libraries"\\"'
OreganoModelDir   = '-DOREGANO_MODELDIR=\\""'+SrcEnv['OREGANODIR']+'/models"\\"'
OreganoLangDir    = '-DOREGANO_LANGDIR=\\""'+SrcEnv['OREGANODIR']+'"/language-specs\\"'
VersionFlag       = '-DVERSION=\\"'+SrcEnv['VERSION']+'\\"'
DataDir           = '-DDATADIR=\\"'+SrcEnv['DATADIR']+'\\"'
Package           = '-DPACKAGE=\\"oregano\\"'
Prefix            = '-DPREFIX=\\"'+SrcEnv['PREFIX']+'\\"'
GetText           = '-DGETTEXT_PACKAGE=\\"oregano\\"'

SrcEnv.Append (CCFLAGS = [
	Prefix,
	Package,
	GetText,
	DataDir,
	VersionFlag,
	LocaleDir,
	OreganoGladeDir,
	OreganoLibraryDir,
	OreganoModelDir,
	OreganoLangDir
	])

Export ('SrcEnv')

# Files to build oregano binary #
files = Split ("""clipboard.c
	create-wire.c
	cursors.c
	dialogs.c
	errors.c
	file-manager.c
	file.c
	load-library.c
	load-schematic.c
	main.c
	netlist-editor.c
	oregano-config.c
	oregano-utils.c
	part-browser.c
	plot-add-function.c
	plot.c
	save-schematic.c
	schematic-view.c
	settings.c
	sim-settings.c
	simulation.c
	smallicon.c
	splash.c
	stock.c
	xml-helper.c
	engines/liboregano-engines.a
	gplot/liboregano-gplot.a
	model/liboregano-model.a
	sheet/liboregano-sheet.a""")

SConscript ('gplot/SConscript')
SConscript ('model/SConscript')
SConscript ('sheet/SConscript')
SConscript ('engines/SConscript')

SrcEnv.Append (CCFLAGS = Split ("-I./src -I./src/model -I./src/sheet -I./src/gplot -I./data/dialogs -I./src/engines"))

oregano = SrcEnv.Program ('oregano', files)

# Install alias #
CEnv.Alias('install', CEnv.Install (os.path.join (CEnv['INSTALL_DIR'], 'bin'), oregano))

